### ISSUE TITLE
docker部署出错，Error response from daemon: cannot start a stopped process: unknown

### ISSUE THREAD

**Issue by XUPTSunHui** [WeBankBlockchain/WeBASE#215]
============================================================

              _    _     ______  ___  _____ _____ 
             | |  | |    | ___ \/ _ \/  ___|  ___|
             | |  | | ___| |_/ / /_\ \ `--.| |__  
             | |/\| |/ _ | ___ |  _  |`--. |  __| 
             \  /\  |  __| |_/ | | | /\__/ | |___ 
              \/  \/ \___\____/\_| |_\____/\____/  
    
============================================================
==============      checking envrionment      ==============
check git...
check finished sucessfully.
check openssl...
check finished sucessfully.
check curl...
check finished sucessfully.
check wget...
check finished sucessfully.
check dos2unix...
check finished sucessfully.
check Docker...
Try to start Docker...
check finished sucessfully.
check docker-compose...
check finished sucessfully.
check config webase v1.5.4 and fisco version 2.8.0...
check finished sucessfully.
check host free memory and cpu core...
check finished sucessfully.
check FISCO-BCOS node port...
check finished sucessfully.
check WeBASE-Web port...
check finished sucessfully.
check WeBASE-Node-Manager port...
check finished sucessfully.
check WeBASE-Sign port...
check finished sucessfully.
check WeBASE-Front port...
check finished sucessfully.
==============      checking    mysql           ==============
use [mysql in docker], skip check mysql
==============        mysql    available       ==============
==============      envrionment available     ==============
============================================================
==============        starting  deploy        ==============
============================================================
==============      Installing FISCO-BCOS     ==============
Build chain script “build_chain.sh” already exists. Re-download it or not? [y/n]: n
FISCO-BCOS node directory “nodes” already exists. Reinstall or not?[y/n]:n
==============      Starting FISCO-BCOS       ==============
try to start node0
try to start node1
64cd40a3655ef8b3c325ca02939c95902ddb08be2bb6b00046b233b1c89ea707
e26dd6d14bf017590335067bb58338794f871284c2b9a4d948a01b695e0339d0
docker: Error response from daemon: cannot start a stopped process: unknown.
docker: Error response from daemon: cannot start a stopped process: unknown.
  Exceed waiting time. Please try again to start node0 
  Exceed waiting time. Please try again to start node1 
Error: No such object: homexupterapplicationwebase-deploynodes127.0.0.1node1
Error: No such object: homexupterapplicationwebase-deploynodes127.0.0.1node0
==============      FISCO-BCOS  Started       ==============
configure nginx.conf file of webase-web
end nginx configuration
update mysql configuration in yaml
using [mysql in docker] mode
end mysql configuration in yaml
update webase-sign configuration in yaml
end webase-sign configuration in yaml
update webase-front configuration in yaml
end webase-front configuration in yaml
update webase-node-mgr configuration in yaml
end webase-node-mgr configuration in yaml
update webase-web configuration in yaml
end webase-web configuration in yaml
check database if exist in [docker mysql]
end check mysql databases
Traceback (most recent call last):
  File "deploy.py", line 127, in <module>
    do()
  File "deploy.py", line 42, in do
    commBuild.docker_do()
  File "/home/xupter/application/webase-deploy/comm/build.py", line 66, in docker_do
    docker.installDockerAll()
  File "/home/xupter/application/webase-deploy/comm/docker.py", line 19, in installDockerAll
    startDockerCompose()
  File "/home/xupter/application/webase-deploy/comm/docker.py", line 25, in startDockerCompose
    doCmd("docker-compose up -d") 
  File "/home/xupter/application/webase-deploy/comm/utils.py", line 111, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : docker-compose up -d, status is 1 ,output is Network docker_default  Creating
Network docker_default  Created
Container mysql-webase-23306  Creating
Container mysql-webase-23306  Created
Container webase-sign-5004  Creating
Container webase-sign-5004  Created
Container webase-front-5002  Creating
Container webase-front-5002  Created
Container webase-node-mgr-5001  Creating
Container webase-node-mgr-5001  Created
Container webase-web-5000  Creating
Container webase-web-5000  Created
Container mysql-webase-23306  Starting
Error response from daemon: cannot start a stopped process: unknown

**Comment by XUPTSunHui** [comment]
webase服务容器能正常启动，节点无法启动

**Comment by CodingCattwo** [comment]
> webase服务容器能正常启动，节点无法启动

最后节点无法启动？可以检查一下docker的配置有无问题
