### ISSUE TITLE
centos7.9 部署 报错 无效的token

### ISSUE THREAD

**Issue by wangxiaocai12138** [WeBankBlockchain/WeBASE#228]
不管是一键部署但是单模块一个个模块的部署，在启动后WeBASE-Node-Manager模块后（启动无报错），访问WeBASE-Web 验证码无法刷新出来，页面提示报错 无效token，查官方文档只有一个错误码202052，其他的没了~。求知道的大佬解答下，
下面是报错的接口及返回信息：
Request URL: [http://127.0.0.1:5000/mgr/WeBASE-Node-Manager/account/pictureCheckCode](https://gitee.com/link?target=http%3A%2F%2F127.0.0.1%3A5000%2Fmgr%2FWeBASE-Node-Manager%2Faccount%2FpictureCheckCode)
Request Method: GET
Status Code: 400
Remote Address: 127.0.0.1:5000
Referrer Policy: strict-origin-when-cross-origin
返回：
{"code":202052,"message":"invalid token","data":null,"attachment":null}
下面是报错信息：
[ERROR][2022-08-07 10:11:28.839][http-nio-5001-exec-1][wsweb][2224][2224][LOG_POINT]not found token
[ERROR][2022-08-07 10:11:28.841][http-nio-5001-exec-1][wsweb][2224][2224][LOG_POINT]catch business exception:[]
com.webank.webase.node.mgr.base.exception.NodeMgrException: invalid token
at com.webank.webase.node.mgr.tools.NodeMgrTools.getToken(NodeMgrTools.java:462) ~[WeBASE-Node-Manager.jar:?]
at com.webank.webase.node.mgr.account.AccountService.getCurrentAccount(AccountService.java:284) ~[WeBASE-Node-Manager.jar:?]
at com.webank.webase.node.mgr.config.security.filter.AccountFilter.preHandle(AccountFilter.java:43) ~[WeBASE-Node-Manager.jar:?]
at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:143) ~[spring-webmvc-5.1.19.RELEASE.jar:5.1.19.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1035) [spring-webmvc-5.1.19.RELEASE.jar:5.1.19.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.1.19.RELEASE.jar:5.1.19.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.1.19.RELEASE.jar:5.1.19.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.1.19.RELEASE.jar:5.1.19.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) [tomcat-embed-core-9.0.39.jar:4.0.FR]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.1.19.RELEASE.jar:5.1.19.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.39.jar:4.0.FR]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:327)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:106)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:87)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)[spring−web−5.2.15.RELEASE.jar:5.2.15.RELEASE]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)[spring−web−5.2.15.RELEASE.jar:5.2.15.RELEASE]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336)[spring−security−web−5.4.4.jar:5.4.4]atorg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)[spring−web−5.2.15.RELEASE.jar:5.2.15.RELEASE]atorg.springframework.security.web.FilterChainProxyVirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.4.4.jar:5.4.4]
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:398) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:257) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:352) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.coyote.AbstractProtocolConnectionHandler.process(AbstractProtocol.java:868)[tomcat−embed−core−9.0.39.jar:9.0.39]atorg.apache.tomcat.util.net.NioEndpointSocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.39.jar:9.0.39]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.39.jar:9.0.39]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:628)[?:?]atorg.apache.tomcat.util.threads.TaskThreadWrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.39.jar:9.0.39]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by zlcolin** [comment]
不能算问题，首次请求校验不太合理。 你验证码重填一下就可以了。

**Comment by wangxiaocai12138** [comment]
大哥不看清问题的吗。验证码都加载不出来怎么填。

**Comment by lanceyan** [comment]
同样的问题，加载不出来验证码
![image](https://user-images.githubusercontent.com/4448746/196906889-54ae987b-d81d-4963-b0c2-1e5fa2d9fd4d.png)

**Comment by lanceyan** [comment]
同样的问题，加载不出来
![image](https://user-images.githubusercontent.com/4448746/196907087-b979fc84-113b-43a3-ac25-b90f026aba70.png)

**Comment by wangxiaocai12138** [comment]
你用是版本的Linux？

**Comment by lanceyan** [comment]
> 你用是版本的Linux？

CentOS Linux release 7.5.1804 (Core)

**Comment by wangxiaocai12138** [comment]
换成Ubuntu的就可以了  ，不知道为什么 CentOS的部署出来会有这个问题

**Comment by lanceyan** [comment]
> 换成Ubuntu的就可以了 ，不知道为什么 CentOS的部署出来会有这个问题

还要换系统吗？ignoreCheckFront: /account/login,/account/pictureCheckCode   这个是不是可以忽略

**Comment by wangxiaocai12138** [comment]
换了系统就没这个问题了  当时我是这么解决的。 Ubuntu的一遍过。。实在是让人无语
