### ISSUE TITLE
WeBASE-Front 启动不了 - std::exception::what: The websocket connection handshake timeout

### ISSUE THREAD

**Issue by zlcolin** [WeBankBlockchain/WeBASE#234]
WeBASE-Front 启动不了  版本如下 
CentOS Linux release 7.9.2009 (Core) /openjdk version "1.8.0_342"
webase.web.version=lab-rc2
webase.mgr.version=lab-rc2
webase.sign.version=lab-rc2
webase.front.version=lab-rc2
fisco.version=v3.0.0-rc4    

cat WeBASE-Front-error.log 
2022-08-16 15:37:43.497 [main] ERROR SpringApplication() - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contractService': Unsatisfied dependency expressed through field 'transService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transService': Unsatisfied dependency expressed through field 'web3ApiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'web3ApiService': Unsatisfied dependency expressed through field 'rpcWeb3j'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rpcClient' defined in class path resource [com/webank/webase/front/base/config/Web3Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.fisco.bcos.sdk.client.Client]: Factory method 'getRpcWeb3j' threw exception; nested exception is org.fisco.bcos.sdk.jni.common.JniException: /github/home/.hunter/_Base/8330e78/8cf628f/3d1dff9/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(88): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout

	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at com.webank.webase.front.Application.main(Application.java:48) [WeBASE-Front.jar:?]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transService': Unsatisfied dependency expressed through field 'web3ApiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'web3ApiService': Unsatisfied dependency expressed through field 'rpcWeb3j'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rpcClient' defined in class path resource [com/webank/webase/front/base/config/Web3Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.fisco.bcos.sdk.client.Client]: Factory method 'getRpcWeb3j' threw exception; nested exception is org.fisco.bcos.sdk.jni.common.JniException: /github/home/.hunter/_Base/8330e78/8cf628f/3d1dff9/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(88): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout

	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.2.20.RELEASE.jar:5.2.20.RELEASE]
	... 21 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'web3ApiService': Unsatisfied dependency expressed through field 'rpcWeb3j'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rpcClient' defined in class path resource [com/webank/webase/front/base/config/Web3Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.fisco.bcos.sdk.client.Client]: Factory method 'getRpcWeb3j' threw exception; nested exception is org.fisco.bcos.sdk.jni.common.JniException: /github/home/.hunter/_Base/8330e78/8cf628f/3d1dff9/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(88): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout

**Comment by ZolHo** [comment]
你好，请问解决了吗，同样的问题卡在这里。

**Comment by CodingCattwo** [comment]
WeBASE lab-rc2版本支持FISCO BCOS 3.0.0-rc2版本，可以参考Changelog选择对应的兼容版本。
推荐直接使用最新的3.0.0及以上正式版
