### ISSUE TITLE
一键部署后，startAll与stopAll无法使用

### ISSUE THREAD

**Issue by noneowl** [WeBankBlockchain/WeBASE#295]
=======      WeBASE-Web     is not running! =======
Traceback (most recent call last):
  File "deploy.py", line 127, in <module>
    do()
  File "deploy.py", line 30, in do
    commBuild.end()
  File "/home/owl/webase-deploy/comm/build.py", line 94, in end
    stopManager()
  File "/home/owl/webase-deploy/comm/build.py", line 512, in stopManager
    result = doCmd("bash stop.sh")
  File "/home/owl/webase-deploy/comm/utils.py", line 111, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : bash stop.sh, status is 127 ,output is bash: stop.sh: 没有那个文件或目录

**Comment by CodingCattwo** [comment]
请检查webase-deploy中webase-node-mgr的文件夹是否存在，文件夹内是否为空。此处为node-mgr的启动停止脚本找不到了
